// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZvD_5kdC3htalcdbH_zC_4GBsg0CcBc',
    appId: '1:279486436114:web:d4958ce0ebe2171c2b99cb',
    messagingSenderId: '279486436114',
    projectId: 'gotstuck-db056',
    authDomain: 'gotstuck-db056.firebaseapp.com',
    storageBucket: 'gotstuck-db056.appspot.com',
    measurementId: 'G-M0S43R31LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0qLWCUgM4kDI7b22_fy8juSlDKk9U1c',
    appId: '1:279486436114:android:9e31cf84415b54102b99cb',
    messagingSenderId: '279486436114',
    projectId: 'gotstuck-db056',
    storageBucket: 'gotstuck-db056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9FFmupTa2cabDNGe7XfP9RI7C1VUF6Y',
    appId: '1:279486436114:ios:5814565c65edb68c2b99cb',
    messagingSenderId: '279486436114',
    projectId: 'gotstuck-db056',
    storageBucket: 'gotstuck-db056.appspot.com',
    iosClientId: '279486436114-i9uvhnh7phom87tgmj1fg5rgpara2lpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotStuck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9FFmupTa2cabDNGe7XfP9RI7C1VUF6Y',
    appId: '1:279486436114:ios:5814565c65edb68c2b99cb',
    messagingSenderId: '279486436114',
    projectId: 'gotstuck-db056',
    storageBucket: 'gotstuck-db056.appspot.com',
    iosClientId: '279486436114-i9uvhnh7phom87tgmj1fg5rgpara2lpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotStuck',
  );
}
